spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/json_annotations
    username: root
    password: Jabee@8598
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create